# Generated by Django 6.0.8 on 2026-09-08 18:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Tavsifi"),
                ),
            ],
            options={
                "verbose_name": "Lavozim",
                "verbose_name_plural": "Lavozimlar",
                "db_table": "hr_position",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="F.I.Sh.")),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Manzil"
                    ),
                ),
                (
                    "passport_seria",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Passport seriyasi",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Passport raqami",
                    ),
                ),
                (
                    "jsshr",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="JSHSHIR"
                    ),
                ),
                (
                    "stir",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="STIR"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Telefon raqami",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Tavsifi"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organization.branch",
                        verbose_name="Filial",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organization.district",
                        verbose_name="Tuman",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organization.region",
                        verbose_name="Viloyat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xodim",
                "verbose_name_plural": "Xodimlar",
                "db_table": "hr_employee",
            },
        ),
        migrations.CreateModel(
            name="EmployeeLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("recruitment", "Ishga olish"),
                            ("dismissal_work", "Ishdan bo'shatish"),
                            ("change_position", "Lavozim o'zgarishi"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_ledgers",
                        to="organization.branch",
                        verbose_name="Filial",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledgers",
                        to="hr.employee",
                        verbose_name="Xodim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xodim daftari yozuvi",
                "verbose_name_plural": "Xodim daftari yozuvlari",
                "db_table": "hr_employee_ledger",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentDismissal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("recruitment", "Ishga olish"),
                            ("dismissal", "Ishdan chiqarish"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(max_length=255, verbose_name="Karta raqami"),
                ),
                (
                    "card_image",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Karta rasmi",
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("fixed_amount", "Belgilangan summa"),
                            ("sales_percent", "Savdodan foiz"),
                            ("founder", "Asoschi"),
                        ],
                        max_length=20,
                        verbose_name="Oylik turi",
                    ),
                ),
                (
                    "fix_summa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Belgilangan summa",
                    ),
                ),
                (
                    "fix_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Belgilangan foiz",
                    ),
                ),
                ("rec_dism_date", models.DateField(verbose_name="Hujjat sanasi")),
                (
                    "dismissal_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Bo'shatish sababi"
                    ),
                ),
                (
                    "extra_summa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Qo'shimcha summa",
                    ),
                ),
                (
                    "extra_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Qo'shimcha foiz",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_dismissals",
                        to="organization.branch",
                        verbose_name="Filial",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_dismissals",
                        to="hr.employee",
                        verbose_name="Xodim",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_dismissals",
                        to="hr.position",
                        verbose_name="Lavozim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ishga olish / bo'shatish",
                "verbose_name_plural": "Ishga olish / bo'shatishlar",
                "db_table": "hr_recruitment_dismissal",
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Tavsifi"),
                ),
                ("from_date", models.DateField(verbose_name="Boshlanish sanasi")),
                ("to_date", models.DateField(verbose_name="Tugash sanasi")),
                ("from_hour", models.TimeField(verbose_name="Boshlanish vaqti")),
                ("to_hour", models.TimeField(verbose_name="Tugash vaqti")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_schedules",
                        to="organization.branch",
                        verbose_name="Filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ish jadvali",
                "verbose_name_plural": "Ish jadvallari",
                "db_table": "hr_work_schedule",
            },
        ),
        migrations.CreateModel(
            name="WorkScheduleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("full_holiday", "To'liq bayram"),
                            ("partial_workday", "Qisman ish kuni"),
                            ("full_workday", "To'liq ish kuni"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Kun turi",
                    ),
                ),
                ("day_date", models.DateField(verbose_name="Sana")),
                ("from_hour", models.TimeField(verbose_name="Boshlanish vaqti")),
                ("to_hour", models.TimeField(verbose_name="Tugash vaqti")),
                (
                    "work_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="hr.workschedule",
                        verbose_name="Ish jadvali",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ish jadvali kuni",
                "verbose_name_plural": "Ish jadvali kunlari",
                "db_table": "hr_work_schedule_item",
            },
        ),
    ]
