# Generated by Django 6.0.8 on 2026-09-08 18:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Tavsifi"),
                ),
            ],
            options={
                "verbose_name": "Dizayn",
                "verbose_name_plural": "Dizaynlar",
                "db_table": "catalog_design",
            },
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Tavsifi"),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=7,
                        verbose_name="HEX rang (#RRGGBB)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rang",
                "verbose_name_plural": "Ranglar",
                "db_table": "catalog_product_color",
            },
        ),
        migrations.CreateModel(
            name="Quality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Tavsifi"),
                ),
            ],
            options={
                "verbose_name": "Sifat",
                "verbose_name_plural": "Sifatlar",
                "db_table": "catalog_quality",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Tavsifi"),
                ),
            ],
            options={
                "verbose_name": "O'lchov birligi",
                "verbose_name_plural": "O'lchov birliklari",
                "db_table": "catalog_unit",
            },
        ),
        migrations.CreateModel(
            name="DesignPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "photo_path",
                    models.CharField(max_length=255, verbose_name="Fayl yo'li"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Tavsifi"),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="catalog.design",
                        verbose_name="Dizayn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dizayn fotosurati",
                "verbose_name_plural": "Dizayn fotosuratlari",
                "db_table": "catalog_design_photo",
            },
        ),
        migrations.AddField(
            model_name="design",
            name="quality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="designs",
                to="catalog.quality",
                verbose_name="Sifat",
            ),
        ),
        migrations.CreateModel(
            name="ProductParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Yaratilgan vaqti",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "party_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Partiya raqami",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Tavsifi"),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Shtrix-kod",
                    ),
                ),
                (
                    "is_runner",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Yo'lak (runner)"
                    ),
                ),
                (
                    "price_per_sqm_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="1 kv.m tannarx (kirish narxi)",
                    ),
                ),
                (
                    "price_per_sqm_sale",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="1 kv.m sotuv narxi",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_parties",
                        to="organization.branch",
                        verbose_name="Filial",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_parties",
                        to="catalog.productcolor",
                        verbose_name="Rang",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_parties",
                        to="catalog.design",
                        verbose_name="Dizayn",
                    ),
                ),
                (
                    "quality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_parties",
                        to="catalog.quality",
                        verbose_name="Sifat",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_parties",
                        to="catalog.unit",
                        verbose_name="O'lchov birligi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot partiyasi",
                "verbose_name_plural": "Mahsulot partiyalari",
                "db_table": "catalog_product_party",
            },
        ),
    ]
